version: "3"
services:
  #++ Eclipse Habmaps UI
  habmaps:
    image: alpeza/alpezahabmaps:latest
    depends_on:
      - mosquitto
    ports:
      - "5000:5000"
      - "80:3000"
    environment:
      HABMAPS_CONFIGURATION: |
        mqtt:
          url: 'mosquitto'
          port: 1883
        db:
          path: '../db.json'
        ui:
          users:
            - admin: admin
        sharedconfs:
          advertisedHostName:
            mosquittows: ws://amazon.web.services.es.com:8081sa
        listeners:
          FrameParser:
            topic: 'hablistener' #Topic principal
            broadcast:
              - service: 'status'
                topic: 'devices/status'
              - service: 'tracespoly'
                topic: '/devices/tracespoly'
                samples: 5000
              - service: 'lastframe'
                topic: '/devices/lastframe'
  #************************************
  #++ Eclipse mosquitto
  mosquitto:
    image: eclipse-mosquitto:latest
    hostname: mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "8081:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/mosquitto.passwd:/mosquitto/config/mosquitto.passwd
  #************************************
  #++ Elastic ++
  #elasticsearch:
  #  image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
  #  environment:
  #    - cluster.name=docker-cluster
  #    - bootstrap.memory_lock=true
  #    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #  ulimits:
  #    memlock:
  #      soft: -1
  #      hard: -1
  #  ports:
  #    - "9200:9200"
  #kibana:
  #  image: docker.elastic.co/kibana/kibana:7.11.2
  #  ports:
  #    - "5601:5601"
