version: "3.5"
services:
  #++ Eclipse Habmaps UI
  habmaps:
    image: alpeza/alpezahabmaps:latest
    ports:
      - "5000:5000"
      - "80:3000"
    environment:
      HABMAPS_CONFIGURATION: |
        mqtt:
          url: 'mosquitto'
          port: 1883
        db:
          path: '../db.json'
        listeners:
          FrameParser:
            topic: 'hablistener'
            broadcast:
              - service: 'status'
                topic: 'devices/status'
              - service: 'tracespoly'
                topic: '/devices/tracespoly'
                samples: 50
              - service: 'lastframe'
                topic: '/devices/lastframe'
  #++ Eclipse mosquitto
  mosquitto:
    image: eclipse-mosquitto:latest
    hostname: mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "8081:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  #++ Elastic
