# Configuracion de la comunicación con el broker mqtt
mqtt:
  url: 'localhost'
  port: 1883
db:
  path: '../db.json'
listeners:
  FrameParser:
    topic: 'hablistener' #Topic principal
    broadcast:
      - service: 'status'
        topic: 'devices/status'
      - service: 'tracespoly'
        topic: '/devices/tracespoly'
        samples: 50
      - service: 'lastframe'
        topic: '/devices/lastframe'
