db:
  path: ../db.json
listeners:
  FrameParser:
    broadcast:
    - service: status
      topic: devices/status
    - samples: 5000
      service: tracespoly
      topic: /devices/tracespoly
    - service: lastframe
      topic: /devices/lastframe
    topic: hablistener
mqtt:
  port: 1883
  url: localhost
sharedconfs:
  advertisedHostName:
    mosquittows: ws://192.168.1.13:8081/socket
  elasticsearch:
    Connection_RFC1738: http://elastic:elastic@localhost:9200
    index: unindice
    topic: hablistener
  mosquitto:
    password: root
    username: habmaps
ui:
  users:
  - admin: admin
