db:
  path: ../db.json
listeners:
  FrameParser:
    topic: hablistener
    broadcast:
    - service: status
      topic: devices/status
    - samples: 5000
      service: tracespoly
      topic: /devices/tracespoly
    - service: lastframe
      topic: /devices/lastframe
mqtt:
  port: 1883
  url: localhost
sharedconfs:
  advertisedHostName:
    mosquittows: ws://192.168.1.13:8081/socket
  mosquitto:
    username: habmaps
    password: root
  elasticsearch:
    index: indicehab
    topic: hablistener
    Connection_RFC1738: http://elastic:elastic@localhost:9200
ui:
  users:
  - admin: admin
