version: "3"
services:
  #************************************
  #++ Habmaps UI
  habmaps:
    image: habmaps4pi:latest
    depends_on:
      - mosquitto
    ports:
      - "5000:5000"
      - "80:3000"
    environment:
      TZ: Europe/Madrid
      HABMAPS_CONFIGURATION: |
        db:
          path: ../db.json
        listeners:
          FrameParser:
            topic: hablistener
            broadcast:
              - service: status
                topic: devices/status
              - samples: 5000
                service: tracespoly
                topic: /devices/tracespoly
              - service: lastframe
                topic: /devices/lastframe
        mqtt:
          port: 1883
          url: mosquitto
        sharedconfs:
          advertisedHostName:
            mosquittows: ws://192.168.1.13:8081/socket
          mosquitto:
            username: habmaps
            password: root
          elasticsearch:
            index: indicehab
            topic: hablistener
            Connection_RFC1738: http://elastic:elastic@elasticsearch:9200
        ui:
          users:
            - admin: admin
  #************************************
  #++ Eclipse mosquitto
  mosquitto:
    image: eclipse-mosquitto:latest
    hostname: mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "8081:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/mosquitto.passwd:/mosquitto/config/mosquitto.passwd
